# Add MySQL client and other required packages
[phases.install]
cmds = [
  "apt-get update && apt-get install -y default-mysql-client",
  "composer install --no-dev --prefer-dist --optimize-autoloader",
  "npm ci"
]

[phases.build]
cmds = ["npm run prod"]

[phases.setup]
cmds = [
  "mkdir -p /var/log/nginx",
  "mkdir -p /var/cache/nginx",
  "chmod -R ug+rwX storage bootstrap/cache"
]

# Use a more robust start command that handles database setup properly
[start]
cmd = "bash -c 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000'"

# Add environment variables for the build
[variables]
NODE_ENV = "production"
